services:
  - type: web
    name: bot-investigador
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: HOTMART_CLIENT_ID
        sync: false
      - key: HOTMART_CLIENT_SECRET
        sync: false
      - key: HOTMART_TOKEN
        sync: false
